name: Build and publish
on: workflow_dispatch
  
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'ApiFootball'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=1.0.$BUILD_NUMBER
      
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://int.nugettest.org' -ApiKey ${{secrets.NUGET_API_KEY}}
